name: DuckandGooseBrewing
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a6ba3'
    - '#ffffff'
    - '#7f97c0'
    - '#b6c1da'
    - '#6180b1'
  brandStrength: 0.2783360327593982
  lightness: 0.11638170690275729
  saturation: 0.6671324407216161
  rhythmicContrast: 0.4901072271168232
purpose: []
